bool is_check
---
uint8 vehicle_state
uint8 control_mode
float32 battery_voltage
uint16 error_code

# uint8 VehicleStateNormal = 0
# uint8  VehicleStateEStop = 1
# uint8  VehicleStateException = 2

# uint8  CONTROL_MODE_RC = 0
# uint8  CONTROL_MODE_CAN = 1
# uint8  CONTROL_MODE_UART = 2

# uint16 SYSTEM_ERROR_MOTOR_DRIVER_MASK 0x0100
# uint16 SYSTEM_ERROR_HL_COMM_MASK 0x0200
# uint16 SYSTEM_ERROR_BATTERY_FAULT_MASK ((uint16_t)0x0001)
# uint16 SYSTEM_ERROR_BATTERY_WARNING_MASK ((uint16_t)0x0002)
# uint16 SYSTEM_ERROR_RC_SIGNAL_LOSS_MASK ((uint16_t)0x0004)
# uint16 SYSTEM_ERROR_MOTOR1_COMM_MASK ((uint16_t)0x0008)
# uint16 SYSTEM_ERROR_MOTOR2_COMM_MASK ((uint16_t)0x0010)
# uint16 SYSTEM_ERROR_MOTOR3_COMM_MASK ((uint16_t)0x0020)
# uint16 SYSTEM_ERROR_MOTOR4_COMM_MASK ((uint16_t)0x0040)
# uint16 SYSTEM_ERROR_STEER_ENCODER_MASK ((uint16_t)0x0080)